/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Active': '激活',
    'Age': '年龄\t',
    'Beggar': '乞丐',
    'Beggar lvl': '乞丐等级',
    'House': '房子',
    'Holy knight': '圣骑士',
    'Import': '导入',
    'Import/export save': '导入/导出存档',
    'Farmer': '农民',
    'Export': '导出',
    'Evil': '邪恶',
    'Evil control': '邪恶控制',
    'Expense/day': '费用/天',
    'years': '年',
    'Xp/day': '经验/天',
    'xp multipliers': '经验加成',
    'Xp left': '经验剩余',
    'Level': '等级',
    'Library': '图书馆',
    'Mage': '法师',
    'Lifespan': '寿命',
    'Magic': '魔法',
    'Master wizard': '大师级法师',
    'Max level': '最高级',
    'Miner': '矿工',
    'Misc': '杂项',
    'Jobs': '工作',
    'Skills': '技能',
    'Shop': '商店',
    'Play': '继续',
    'Pause': '暂停',
    'Personal squire': '私人护卫',
    'Required: ': '要求: ',
    'Reset': '重置',
    'Sapphire charm': '蓝宝石护符',
    'Settings': '设置',
    'Skip': '跳过',
    'Squire': '护卫',
    'Student': '学生',
    'Steel longsword': '钢长剑',
    'Study desk': '书桌',
    'Task': '任务',
    'Toggle': '切换',
    'Touch the eye': '触摸眼球',
    'Wizard': '巫师',
    'Wooden hut': '木屋',
    'Properties': '属性',
    'Progress Knight': '骑士进度条',
    'Small palace': '小宫殿',
    'Strength': '力量',
    'Tent': '帐篷',
    'The Arcane Association': '奥术协会',
    'Veteran footman': '资深步兵',
    'Veteran knight': '资深骑士',
    'Toggle light/dark mode': '切换亮/暗模式',
    'Time warping': '时间扭曲',
    'Amulet': '护身符',
    'Age has caught up to you': '年龄已经赶上了你',
    'Apprentice mage': '学徒法师',
    'Auto-learn': '自动学习',
    'Auto-promote': '自动提升',
    'Book': '书',
    'Chairman': '会长',
    'Combat': '战斗',
    'Cottage': '茅屋',
    'Current job': '当前工作',
    'Current skill': '当前技能',
    'Dark magic': '黑暗魔法',
    'Super immortality': '超级永生',
    'Net/day': '净/天',
    'Muscle memory': '肌肉记忆',
    'Military': '军队',
    'Merchant': '商人',
    'Meditation': '冥想',
    'Large house': '大房子',
    'Knight': '骑士',
    'Join the discord community!': '加入discord社区！',
    'Intimidation': '威胁',
    'Immortality': '永生',
    'Income/day': '收入/天',
    'Homeless': '无家可归',
    'Hard reset game': '硬重置',
    'Grand palace': '大宫殿',
    'Fundamentals': '基础知识',
    'Elite knight': '精英骑士',
    'Effect': '效果',
    'Dumbbells': '哑铃',
    'Day': '，天数\t',
    'Demon training': '魔鬼训练',
    'Disable warp': '禁用扭曲',
    'Common work': '常规工作',
    'Butler': '男仆',
    'Blood meditation': '血之冥想',
    'Concentration': '专注',
    'Bargaining': '讨价还价',
    'Battle tactics': '战斗战术',
    'Blacksmith': '铁匠',
    'Affects game speed': '影响游戏速度',
    'Affects dark magic xp gain': '影响黑魔法经验收益',
    'Affects all xp gain': '影响所有经验收益',
    'Concentration lvl': '专注等级',
    'evil': '邪恶',
    'Fisherman': '渔夫',
    'Footman': '步兵',
    'Happiness': '幸福',
    'Balance (in coins': '余额 (以硬币计',
    'Legendary knight': '传奇骑士',
    'Farmer lvl': '农民等级',
    'Enable warp': '启用扭曲',
    'Embrace evil': '拥抱邪恶',
    'Demon\'s wealth': '恶魔的财富',
    'Bargaining lvl': '讨价还价等级',
    'Fisherman lvl': '渔夫等级',
    'Strength lvl': '力量等级',
    'Productivity lvl': '生产力等级',
    'Squire lvl': '护卫等级',
    'Meditation lvl': '冥想等级',
    'Miner lvl': '矿工等级',
    'Veteran Knight lvl': '资深骑士等级',
    'Merchant lvl': '商人等级',
    'Footman lvl': '步兵等级',
    'Veteran footman lvl': '资深步兵等级',
    'Knight lvl': '骑士等级',
    'Blacksmith lvl': '铁匠等级',
    'Mana control lvl': '法力控制等级',
    'Muscle memory lvl': '肌肉记忆等级',
    'Elite knight lvl': '精英骑士等级',
    'Student lvl': '学生等级',
    'Mage lvl': '法师等级',
    'Wizard lvl': '巫师等级',
    'Intimidation lvl': '威胁等级',
    'Time warping lvl': '时间扭曲等级',
    'Evil control lvl': '邪恶控制等级',
    'Chairman lvl': '会长等级',
    'Legendary knight lvl': '传奇骑士等级',
    'Demon training lvl': '魔鬼训练等级',
    'Master wizard lvl': '大师级法师等级',
    'Immortality lvl': '永生等级',
    'Holy Knight lvl': '圣骑士等级',
    'Apprentice mage lvl': '学徒法师等级',
    'Obliterate squadrons of enemy soldiers in one go with extraordinary proficiency, while equipped with the finest gear. Such a feared unit on the battlefield is paid extremely well.': '用最精良的装备，一次歼灭敌军中队。这样一支令人敬畏的部队在战场上的薪水非常高。',
    'Much larger than a regular house, which boasts even more rooms and multiple floors. The building is quite spacious but comes with a hefty price tag.': '比普通的房子大得多，普通的房子有更多的房间和多层。这栋建筑很宽敞，但价格不菲。',
    'Lengthen your lifespan through the means of magic. However, is this truly the immortality you have tried seeking for...?': '用魔法延长你的寿命。然而，这真的是你一直在寻找的永生吗?',
    'Create and revise battle strategies, improving experience gained in the military.': '创建和修改作战策略，提高在军队中获得的经验。',
    'Condition your body and strength through harsh training. Stronger individuals are paid more in the military.': '通过艰苦的训练来调节你的身体和力量。更强壮的人在军队中得到更多的报酬。',
    'Collapse entire armies in mere seconds with your magically imbued blade. The handful of elite knights who attain this level of power are showered with coins.': '用你的魔法剑在几秒钟内瓦解整个军队。少数精英骑士获得这个等级的权力会得到大量的金币。',
    'Carry around your knight\'s shield and sword along the battlefield. Very meager pay but the work experience is quite valuable.': '带着你骑士的盾牌和剑沿着战场行进。工资很低，但工作经验很有价值。',
    'Plow the fields and grow the crops. It\'s not much but it\'s honest work.': '犁地，种庄稼。这工作不多，但很正经。',
    ', which will heavily impact your future lives.': '，这将严重影响你未来的生活。',
    'Delve into dangerous caverns and mine valuable ores. The pay is quite meager compared to the risk involved.': '深入危险的洞穴，开采有价值的矿石。与所涉及的风险相比，报酬是相当少的。',
    'Encompass yourself with formidable power bestowed upon you by evil, allowing you to pick up and absorb any job or skill with ease.': '用邪恶赋予你的强大力量包围你自己，让你轻松地获得和吸收任何工作或技能。',
    'Embedded with a rare sapphire, this charm activates more mana channels within your body, providing a much easier time learning magic.': '镶嵌在一颗罕见的蓝宝石上，这个咒语激活你体内更多的魔法通道，让你更容易学习魔法。',
    'Grow and culture the evil within you through the sacrifise of other living beings, drastically increasing evil gain.': '通过其他生物的牺牲来成长和培养你内在的邪恶，急剧增加邪恶收益。',
    'Heavy tools used in strenuous exercise to toughen up and accumulate strength even faster than before.': '在剧烈运动中用来比以前更快地增强和积累力量的重型工具。',
    'Keeps your household clean at all times and also prepares three delicious meals per day, leaving you in a happier, stress-free mood.': '让你的家庭随时保持清洁，每天还准备三顿美味的饭菜，让你在一个更快乐，无压力的心情。',
    'Learn to emit a devilish aura which strikes extreme fear into other merchants, forcing them to give you heavy discounts.': '学会散发一种恶魔的气息，打击其他商家的极度恐惧，迫使他们给你很大的折扣。',
    'Learn to procrastinate less at work and receive more job experience per day.': '学会在工作中减少拖延，每天积累更多的工作经验。',
    'Productivity': '生产力',
    'Put down your life to battle with enemy soldiers. A courageous, respectable job but you are still worthless in the grand scheme of things.': '放下你的生命与敌人的士兵战斗。一份勇敢，体面的工作但你在这个宏伟的计划中仍然毫无价值。',
    'Reel in various fish and sell them for a handful of coins. A relaxing but still a poor paying job.': '钓上各种各样的鱼，然后把它们卖成一把硬币。一份轻松但收入微薄的工作。',
    'Shabby logs and dirty hay glued together with horse manure. Much more sturdy than a tent, however, the stench isn\'t very pleasant.': '破烂的原木和肮脏的干草和马粪粘在一起。虽然比帐篷坚固多了，但是臭气也不太好闻。',
    'Slash and pierce through enemy soldiers with ease, while covered in steel from head to toe. A decently paying and very respectable job.': '从头到脚都裹着钢铁，轻松地刺穿敌军士兵。一份报酬丰厚、非常体面的工作。',
    'Sleep on the uncomfortable, filthy streets while almost freezing to death every night. It cannot get any worse than this.': '睡在不舒服、肮脏的街道上，每天晚上几乎冻死。不会比这更糟了。',
    'Smelt ores and carefully forge weapons for the military. A respectable and OK paying commoner job.': '为军队冶炼矿石，精心锻造武器。一份体面的、报酬不错的普通工作。',
    'Something tells you that the amulet might transform even further after living for': '直觉告诉你，在你完成了第一次重生之后，如果你的年龄（当前年龄，不是寿命上限）超过200岁，这个护身符还可能会带来更大的变化',
    'Spend your days administrating The Arcane Association and investigate the concepts of true immortality. The chairman receives ludicrous amounts of pay daily.': '花时间管理你的神秘协会和调查的概念，真正的永生。会长每天收到的薪水多得可笑。',
    'Study the theory of mana and practice basic spells. There is minor pay to cover living costs, however, this is a necessary stage in becoming a mage.': '学习法术力理论并练习基本法术。 可以支付生活费用的少量薪水，但是，这是成为法师的必经阶段。',
    'Struggle day and night for a couple of copper coins. It feels like you are at the brink of death each day.': '昼夜不停地挣扎着几个铜币。 感觉就像您每天都处在死亡边缘。',
    'Strengthen your neurons through habit and repetition, improving strength gains throughout the body.': '通过习惯和重复来强化你的神经元，改善全身力量的增强。',
    'Structured with a timber frame and a thatched roof. Provides decent living conditions for a fair price.': '用木框架和茅草屋顶建造的。以公平的价格提供体面的生活条件。',
    'Strengthen your mana channels throughout your body, aiding you in becoming a more powerful magical user.': '加强你全身的魔法通道，帮助你成为一个更强大的魔法使用者。',
    'Stores a collection of books, each containing vast amounts of information from basic life skills to complex magic spells.': '储存了大量的书籍，每一本都包含了大量的信息，从基本的生活技能到复杂的魔法咒语。',
    'for your jobs and skills equivalent to': '对你的工作和技能，加成的公式为',
    'Fill your mind with peace and tranquility to tap into greater happiness from within.': '让你的头脑充满和平与安宁，从内心发掘更大的幸福。',
    'Feared worldwide, obliterate entire nations in a blink of an eye. Roughly every century, only one holy knight is worthy of receiving such an esteemed title.': '让全世界都感到恐惧，一眨眼的功夫就把整个国家都毁灭了。大约每个世纪，只有一位神圣骑士配得上这样一个受人尊敬的头衔。',
    'A grand residence completely composed of gold and silver. Provides the utmost luxurious and comfortable living conditions possible for a ludicrous price.': '一座完全由金银构成的宏伟住宅。以可笑的价格提供最豪华和舒适的生活条件。',
    'A fine blade used to slay enemies even quicker in combat and therefore gain more experience.': '在战斗中可以更快地杀死敌人，从而获得更多经验。',
    'A mere human body is too feeble and weak to withstand evil. Train with forbidden methods to slowly manifest into a demon, capable of absorbing knowledge rapidly.': '仅仅是人的身体就太软弱无力，无法抵挡邪恶。用禁止的方法训练，慢慢变成一个能够快速吸收知识的恶魔。',
    'A place to write down all your thoughts and discoveries, allowing you to learn a lot more quickly.': '一个写下你所有想法和发现的地方，让你学得更快。',
    'A thin sheet of tattered cloth held up by a couple of feeble, wooden sticks. Horrible living conditions but at least you have a roof over your head.': '一张由两根软弱的木棒托着的破布。生活条件很糟糕，但至少你有个栖身之所。',
    'A very rich and meticulously built structure rimmed with fine metals such as silver. Extremely high expenses to maintain for a lavish lifestyle.': '一个非常丰富和精心建造的结构，镶有精细的金属，如银。维持奢华的生活方式需要极高的费用。',
    'Assists you in completing day to day activities, giving you more time to be productive at work.': '帮助你完成每天的活动，给你更多的时间在工作中更有效率。',
    'Bend space and time through forbidden techniques, resulting in a faster gamespeed.': '通过禁止的技术扭曲空间和时间，导致更快的游戏速度。',
    'Blessed with unparalleled talent, perform unbelievable feats with magic at will. It is said that a master wizard has enough destructive power to wipe an empire off the map.': '拥有无与伦比的天赋，可以随心所欲地施展难以置信的魔术。据说大师级法师拥有足够的破坏力，足以将一个帝国从地图上抹去。',
    'More experienced and useful than the average footman, take out the enemy forces in battle with your might. The pay is not that bad.': '比普通步兵更有经验，更有用，在战斗中用你的力量消灭敌人。(工资没那么低。)',
    'Study the tricks of the trade and persuasive skills to lower any type of expense.': '学习交易技巧和说服技巧来降低任何类型的费用。',
    'Tame the raging and growing evil within you, improving evil gain in-between rebirths.': '驯服你内心的愤怒和增长的邪恶，在转世之间提高邪恶增益。',
    'This means you will learn everything again much more quickly than you did in your previous life.': '这意味着你学习每一件事的速度要比你以前更快。',
    'Through harnessing ancient, forbidden techniques, lengthen your lifespan drastically beyond comprehension.': '通过利用古老的、被禁止的技术，将你的寿命大大延长到无法理解的程度。',
    'Through the means of dark magic, multiply the raw matter of the coins you receive from your job.': '通过黑魔法，将您从工作中获得的硬币的原始物质相乘。',
    'Travel from town to town, bartering fine goods. The job pays decently well and is a lot less manually-intensive.': '从一个城镇到另一个城镇，以物易物。这份工作报酬不错，而且不需要太多的体力劳动。',
    'Turn the tides of battle through casting intermediate spells and mentor other apprentices. The pay for this particular job is extremely high.': '通过施放中间法术和指导其他学徒来扭转战斗的趋势。这份工作的报酬非常高。',
    'Under the supervision of a mage, perform basic spells against enemies in battle. Generous pay will be provided to cover living costs.': '在法师的指导下，在战斗中对敌人施展基本法术。将提供相当数量的工资以支付生活费用。',
    'Utilise advanced spells to ravage and destroy entire legions of enemy soldiers. Only a small percentage of mages deserve to attain this role and are rewarded with an insanely high pay.': '使用先进的法术来蹂躏和摧毁整个军团的敌人士兵。只有一小部分的法师配得上这个角色，并能得到高得离谱的报酬。',
    'Utilising your unmatched combat ability, slaugher enemies effortlessly. Most footmen in the military would never be able to acquire such a well paying job like this.': '利用你无与伦比的战斗能力，毫不费力地屠杀敌人。军队里的大多数男仆都不可能得到这样一份报酬优厚的工作。',
    'Your age has met your lifespan, use the amulet to rebirth before you pass away': '你的年龄已经达到了你的寿命，用护身符在你死前重生',
    'Improve your learning speed through practising intense concentration activities.': '通过练习集中注意力的活动来提高你的学习速度。',
    'A dedicated area which provides many fine stationary and equipment designed for furthering your progress in research.': '一个专门的区域，提供了许多精致的文具和装备设计，以促进您的研究进展。',
    'A building formed from stone bricks and sturdy timber, which contains a few rooms. Although quite expensive, it is a comfortable abode.': '用石头、砖和坚固的木材建造的建筑，里面有几个房间。虽然很贵，但这是一个舒适的住所。',
    "You become an inquisitive yet putrid creature that siphons life from everything around you.": "你变成了一个好奇而腐烂的生物，从你周围的一切中吸取生命。",
    "You become one with everything.": "你与一切合而为一。",
    "You gazed into the dark heart of the Void long enough to become one of the most powerful and feared beings, all lesser void creatures are at your command.": "你凝视着虚空的黑暗之心足够长的时间，成为最强大和最可怕的生物之一，所有次等虚空生物都在你的指挥下。",
    "You have became the very thing you swore to destroy.": "你已经成为你发誓要摧毁的东西。",
    "You have seen it all, from the very beginning to the very end.": "你已经看到了这一切，从头到尾。",
    "You have unlocked": "你已解锁",
    "You reign the whole nation, while your riches may be corrupted, everything you see belongs to you.": "你统治了整个国家，虽然你的财富可能被腐化，但你所看到的一切都属于你。",
    "You rule your very own community in your small town, owning multiple establishments.": "你在你的小镇上统治着你自己的社区，拥有多个机构。",
    "You sit on your throne, overseeing the existence itself.": "你坐在你的宝座上，监督着存在本身。",
    "You stumble across a strange looking amulet on your 25th birthday. It does not look like\n                                    it has any worth on the market given that it's made from cheap-looking copper. However, you\n                                    feel a weird urge to keep the amulet, so you slip it into your pocket for safekeeping.\n        ": "你在 25 岁生日时偶然发现了一个看起来很奇怪的护身符。它看起来不像\n 它在市场上没有任何价值，因为它是由看起来很便宜的铜制成的。但是，您\n 有一种保留护身符的奇怪冲动，因此您将其放入口袋以妥善保管。\n",
    "You surrender yourself to the Void, making it easier to take control of you.": "你将自己投降于虚空，更容易控制你。",
    "Void Influence": "虚空影响",
    "Void Lord": "虚空领主",
    "Void Manipulation": "虚空操纵",
    "Void Necklace": "虚空项链",
    "Void Orb": "虚空宝珠",
    "Void Realm": "虚空境",
    "Void Reaver": "虚空掠夺者",
    "Void Slave": "虚空奴隶",
    "Void Slave level 0/25, Chairman level 0/": "虚空奴隶等级0/25，主席等级0/",
    "Void Symbiosis": "虚空共生",
    "Void Universe": "虚空宇宙",
    "Void Wraith": "虚空怨灵",
    "When the orb touches non void entities, it instantly disintegrate them. Harnessing its power from Void realm.": "当球体接触到非虚空实体时，它会立即分解它们。利用虚空领域的力量。",
    "With the powers bestowed upon you by an unknown entity you wander around, visiting places revered and feared in search of answers.": "借助未知实体赋予你的力量，你四处游荡，参观受人尊敬和恐惧的地方以寻找答案。",
    "Wooden Hut": "木屋",
    "Current ability": "当前能力",
    "Current class": "当前职业",
    "Damned soul... a shadow of your former self, lingering between realms and consumed by void... can you ever find peace?": "该死的灵魂……你以前的自己的影子，徘徊在各个领域之间，被虚空吞噬……你能找到平静吗？",
    "Dark Influence": "邪恶势力",
    "Dark Knowledge": "黑暗知识",
    "Dark Magic": "黑暗魔法",
    "Demon Training": "恶魔训练",
    "Demon's Wealth": "恶魔的财富",
    "Each day you are succumbing to the Void more and more, can you hold to your humanity for a bit longer, or will you let it devour you?": "每天你都越来越屈服于虚空，你能坚持你的人性更久，还是让它吞噬你？",
    "Epiphany": "顿悟",
    "essence": "精华",
    "Essence": "精华",
    "Essence Collector": "精华收集器",
    "Eternal Wanderer": "永恒的流浪者",
    "Evil Control": "邪恶控制",
    "Evil Incarnate": "邪恶化身",
    "Exploit the unlimited potential of multiverse energies and collect its resources.": "利用多元宇宙能量的无限潜力并收集其资源。",
    "Extremely powerful being with tremedous telekinetic powers and the ability to rearrange the molecular structure of matter and energy, even up to cosmic scale.": "极其强大的存在，具有惊人的远程动力能力和重新排列物质和能量分子结构的能力，甚至达到宇宙尺度。",
    "Feared by nations, obliterate entire armies in a blink of an eye. Roughly every century, only one holy knight is worthy of receiving such an esteemed title.": "万国畏惧，眨眼间歼灭全军。几乎每个世纪，只有一位圣骑士配得上如此尊贵的称号。",
    "for your classes and abilities equivalent to": "你的职业和能力相当于",
    "Forged from void dust and dark matter, can slash through dimensional barriers. It's a weapon of choice for every Void Reaver.": "由虚空尘埃和暗物质锻造而成，可以冲破次元屏障。它是每个虚空掠夺者的首选武器。",
    "From the time the universe was born. Can create another small universes.": "从宇宙诞生之日起。可以创造另一个小宇宙。",
    "Galactic Command": "银河司令部",
    "Galactic Council": "银河委员会",
    "Galactic Throne": "银河王座",
    "Generates an innate armor as a part of you body, which is resistant to attacks, harm or pain.": "生成一种与生俱来的盔甲作为你身体的一部分，它可以抵抗攻击、伤害或疼痛。",
    "Grand Palace": "大宫殿",
    "Helps you shape and manipulate void matter, even transmute it and rebuild into anything of your choosing.": "帮助您塑造和操纵虚空物质，甚至将其转化并重建为您选择的任何东西。",
    "Higher Dimensions": "更高维度",
    "Holy Knight": "圣骑士",
    "If thou gaze long into an abyss, the abyss will also gaze into thee.": "如果你凝视深渊，深渊也会凝视你。",
    "Imperator": "帝王",
    "In a trance like state, you feel the Void controlling your thoughts, perception, memories, emotions and personality.": "在恍惚状态中，你会感觉到虚空控制着你的思想、感知、记忆、情绪和个性。",
    "Large House": "大房子",
    "Lengthen your lifespan drastically beyond comprehension by harnessing ethereal energy.": "通过利用空灵的能量，大大延长您的寿命。",
    "Lets you see memories, remember images, and even see new pictures and ideas.": "让您看到回忆、记住图像，甚至看到新的图片和想法。",
    "Lieutenant General": "中将",
    "Lieutenant General lvl": "中将等级",
    "Life Essence": "生命精华",
    "Mana Control": "法力控制",
    "Master Wizard": "大师级法师",
    "Mastery is achieved when 'telling time' becomes 'telling time what to do'.": "当“告诉时间”变成“告诉时间该做什么”时，就达到了精通。",
    "millennium": "千年",
    "Mind Seize": "夺心",
    "Mind's Eye": "心灵的眼睛",
    "Multiverse Fragment": "多元宇宙碎片",
    "Muscle Memory": "肌肉记忆",
    "Nation Ruler": "国家统治者",
    "Never ending torture, you swore to serve the Void for the rest of your existence.": "永无止境的折磨，你发誓终生为虚​​空服务。",
    "new ability that will boost you even further in your journey.": "新的能力将在你的旅程中进一步推动你。",
    "new ability that will boost you even further in your journey.\n                                        ": "新能力将在您的旅程中进一步推动您。\n",
    "Nova": "新星",
    "Obliterate squadrons of enemy soldiers in one go with extraordinary proficiency, while equipped magically imbued blade. Such a feared unit on the battlefield is paid extremely well.": "以非凡的熟练度一口气消灭敌方士兵的中队，同时装备魔法灌输的刀片。战场上这样一个令人恐惧的单位，薪水非常好。",
    "Observatory": "天文台",
    "One Above All": "最重要的一个",
    "Parallel Universe": "平行宇宙",
    "Personal Squire": "个人侍从",
    "Pocket Dimension": "口袋尺寸",
    "Predating our own universe, the Void has an ulimited amount of space for your belongings, if you are willing to submit to it.": "早于我们自己的宇宙，虚空有无限的空间存放你的物品，如果你愿意服从的话。",
    "Primordial being that predate the universe, involved with the creation of life and powerful beyond mortal comprehension, existing as myths to the oldest species in the universe.": "早于宇宙的原始生物，与生命的创造有关，具有超越凡人理解的强大能力，作为宇宙中最古老物种的神话而存在。",
    "Purest version of void created material, a teaspoon of it is as heavy as a small planet.": "最纯粹的虚空创造材料，一茶匙就跟一颗小行星一样重。",
    "Sapphire Charm": "蓝宝石吊饰",
    "Save profile with: Alt + \"1-3\" / Load profile with \"1-3\"\t\t\t\t\t\t\t": "保存配置文件： Alt + \"1-3\" / 加载配置文件 \"1-3\"\t\t\t\t\t\t\t",
    "Screaming into existence, you become a manifestation of the unknowable nothingness that lies beyond.": "尖叫着进入存在，你成为超越彼岸的不可知的虚无的化身。",
    "Sealed for a very long time, you utilized these forbidden texts for your own personal gain.": "封印了很长时间，你利用这些禁书为自己谋取私利。",
    "Self-contained plane of existence, co-existing with one's own, helping you restore fragments of your forgotten power.": "自给自足的存在位面，与自己的共存，帮助你恢复被遗忘的力量碎片。",
    "Shortcuts": "捷径",
    "Sigma Proioxis": "西格玛益生菌",
    "Small Palace": "小宫殿",
    "Something tells you that the amulet might evolve after living for": "有人告诉你，护身符可能会在生存后进化",
    "Specialize in harnessing temporal energies that alter the flow of time with supernatural divinations and otherwordly expertise.": "专注于利用时间能量，通过超自然的占卜和其他专业知识改变时间的流动。",
    "Steel Longsword": "钢长剑",
    "Sticky sidebar": "粘性侧边栏",
    "Study Desk": "学习桌",
    "Tapping into the powers of the Void while combining them with evil grants you an ulimited potential.": "在将虚空与邪恶结合的同时，利用虚空的力量赋予你无限的潜力。",
    "Temporal Dimension": "时间维度",
    "ten millenia": "十千年",
    "Ten millenia have passed... most of them spent serving the Void, yet there is still a glimpse of humanity inside of you. All of the sudden your amulet starts to glow in the distance,\n                                        illuminating darkness around you with the brightness of thousand suns. With the very last remnant of your free will you run to your amulet and touch it...": "十千年过去了……他们中的大多数人都在为虚空服务，但你的内心仍然有一丝人性。突然间，你的护身符开始在远处发光，\n 用千日太阳的亮度照亮你周围的黑暗。带着你最后的自由意志，你跑向你的护身符并触摸它......",
    "The most powerful and essential equipment of any Celestial. Acts as a source of infinite power.": "任何天体中最强大和最重要的装备。作为无限力量的源泉。",
    "The power to fulfill absolutely any and all wishes without any limitations.": "绝对满足任何和所有愿望的权力，没有任何限制。",
    "The Void": "虚空",
    "There are few who may tread the paths between worlds, these powers grant you an ability to generate fields of void energy that devour all living things.": "很少有人可以踏上世界之间的道路，这些力量赋予你产生吞噬所有生物的虚空能量场的能力。",
    "Time Loop": "时间循环",
    "Time Warping": "时间扭曲",
    "Town Ruler": "镇长",
    "Transced will only show up if you have": "超越 仅在您有时才会显示",
    "Transcend": "超越",
    "Under the supervision of a skilled mage, perform basic spells against enemies in battle. Generous pay will be provided to cover living costs.": "在熟练的法师的监督下，在战斗中对敌人施展基本法术。将提供丰厚的报酬以支付生活费用。",
    "Universe Fragment": "宇宙碎片",
    "Unknown how or when the Void realm came into existence, containing elements which don’t exist outside of its dimensional plane are now all to your disposal": "未知虚空领域是如何或何时出现的，包含不存在于其次元位面之外的元素现在都由你支配",
    "Used for observing terrestrial, marine and celestial events.": "用于观测陆地、海洋和天体事件。",
    "Veteran Knight": "资深骑士",
    "Void Amplification": "虚空增幅",
    "Void Armor": "虚空护甲",
    "Void Blade": "虚空之刃",
    "Void Dust": "虚空之尘",
    "Void Embodiment": "虚空化身",
    "Void Fiend": "虚空恶魔",
    "Creator of the Void, a vast canvas of blackness and nothingness, in which the concept of its existence defies all logic, nothing will escape you.": "虚空的创造者，一片漆黑和虚无的广阔画布，其中存在的概念违背了所有逻辑，没有什么可以逃脱你的。",
    ", and which will heavily impact your future lives.": "，这将严重影响你未来的生活。",
    ", you will be reborn once again, losing all your coins,": "，您将再次重生，失去所有硬币，",
    "\"Celestial Powers\"": "“天权”",
    "\"Galactic Council\"": "“银河委员会”",
    "\"The Void\"": "“虚空”",
    "A Dimension just for you, that can be summoned at will. What happens there stays there.": "一个专为你而设的维度，可以随意召唤。那里发生的事情留在那里。",
    "A nigh-omnipotent cosmological entity, with vast matter and energy manipulation abilities that help you push the boundaries of the Universe itself.": "一个几乎无所不能的宇宙实体，具有巨大的物质和能量操纵能力，可帮助您突破宇宙本身的界限。",
    "A symbiotic relationship that helps you become one with the Void.": "一种共生关系，可帮助您与虚空合一。",
    "A technique designed to manipulate human thought and action against their desire.": "一种旨在操纵人类思想和行动违背其欲望的技术。",
    "A thousand years have come and gone and yet, you still remain alive... somehow. You feel your amulet shivering again and to your surprise, you see small tendrils\n                                        full of eyeballs emergin from it. As you are about to drop the amulet, you hear frightening screech followed by whispers in your head...": "一千年过去了，然而，你仍然活着……不知何故。你感到你的护身符再次颤抖，令你惊讶的是，你看到小卷须\n长满了眼球。当你即将放下护身符时，你会听到可怕的尖叫声，然后是耳语在你的脑海中......",
    "Abilities": "能力",
    "Abilities can increase its multiplier": "能力可以增加它的乘数",
    "abilities.": "能力。",
    "ability and you will gain": "能力，你将获得",
    "ability unlocked!": "能力解锁！",
    "Absolute power corrupts absolutely.": "绝对权力绝对腐败。",
    "Absolute Wish": "绝对的愿望",
    "Abyss Anomaly": "深渊异常",
    "Abyss God": "深渊之神",
    "Abyss Manipulation": "深渊操纵",
    "Acallaris": "阿卡拉里斯",
    "Adept Mage": "熟练法师",
    "Affects all XP gain": "影响所有 XP 增益",
    "Affects Almightiness XP gain": "影响全能经验获取",
    "Affects dark magic XP gain": "影响黑魔法 XP 增益",
    "All Seeing Eye": "全视之眼",
    "Allows you to shape your own reality within the Void itself.": "允许你在虚空本身中塑造你自己的现实。",
    "Almightiness": "全能",
    "and current levels.\n                                        However your max level won't be erased but multiplied with": "和当前级别。\n 但是，您的最大级别不会被删除，而是乘以",
    "and reach its final form after": "并在之后达到最终形态",
    "and transform even further after living for\n                                        a": "并更进一步在生存\n",
    "Apprentice Mage": "学徒法师",
    "Archmage": "大魔导师",
    "Arrow Keys - Menu navigation\n\t\t\t\t\t\t\t\t\t\t": "箭头键 - 菜单导航\n\t\t\t\t\t\t\t\t\t\t",
    "As the highest rank of T.A.A, all funds go directly to you.": "作为 T.A.A 的最高级别，所有资金都直接归您所有。",
    "As the highest ranking official, you manage and oversee everything that happens, while your pay is astronomical, so are your expenses.": "作为最高级别的官员，您管理和监督发生的一切，而您的薪水是天文数字，您的开支也是如此。",
    "Astral Body": "星体",
    "Astral Realm": "星界",
    "Auto-pause(Void": "自动暂停（虚空",
    "Balance": "平衡",
    "Battle Tactics": "战斗战术",
    "Being able to exist in multiple parallel timelines and manipulating you parallel selves, influencing their lives as you see fit.": "能够存在于多个平行的时间线上并操纵平行的自我，以你认为合适的方式影响他们的生活。",
    "Bend space and time through forbidden techniques, speeding up your learning processes.": "通过禁止的技术弯曲空间和时间，加快你的学习过程。",
    "Beneath personality and ego lays the source of our deep character, our personhood. Here are the psychic senses, our deep mind and emotions, symbols and inner reality.": "在个性和自我之下，是我们深刻性格的源泉，我们的人格。这是精神感官，我们深刻的思想和情感，符号和内在现实。",
    "Blessed with unparalleled talent, perform unbelievable feats with magic at will. It is said that an archamge has enough destructive power to wipe an empire off the map.": "拥有无与伦比的天赋，随心所欲地用魔法完成令人难以置信的壮举。据说大魔王的破坏力足以将一个帝国从地图上抹去。",
    "Blood Meditation": "血液冥想",
    "Born from chaos when the universe was first created, believed to exist in harmony, balancing evil and good.": "宇宙初生时从混沌中诞生，相信和谐共处，平衡善恶。",
    "Brainwashing": "洗脑",
    "By clicking on": "通过点击",
    "By possesing the power to partially alter the laws of physics and transceding lower dimensional spaces, your existence becomes never-ending.": "通过拥有部分改变物理定律和超越低维空间的力量，你的存在变得永无止境。",
    "By proving your skills with a bow, you were appointed to lead a small group of archers to ambush your enemies from a distance.": "通过用弓证明你的技能，你被任命带领一小群弓箭手从远处伏击你的敌人。",
    "Came into existance long before our universe was created, this strange looking object with no shape radiates unlimited energy.": "早在我们的宇宙被创造之前就已经存在了，这个外观奇特、没有形状的物体散发着无限的能量。",
    "Ceaseless Abyss": "无尽深渊",
    "Celestial Powers": "天权",
    "Celestial Robe": "天界长袍",
    "Centenary": "百年纪念",
    "Chronomancer": "时空术士",
    "City Ruler": "城市统治者",
    "class category along with": "类类别以及",
    "Classes": "职业",
    "Corrupted": "腐化",
    "Corrupted by Void, you are slowly turning into a slave with no free will, just to serve the Void for the rest of eternity... Can you resist it, or will it consume you forever?": "被虚空腐化，你正在慢慢变成一个没有自由意志的奴隶，只为永远为虚空服务……你能抗拒它，还是它会永远吞噬你？",
    "Cosmic Longevity": "宇宙寿命",
    "Cosmic Recollection": "宇宙回忆",
    "Creating your own pocket dimension where centuries go by in mere seconds.": "创建您自己的口袋维度，几个世纪就在几秒钟内过去。",
    "Creator of everything.": "一切的创造者。",
    "L - Auto-learn": "L - 自动学习",
    "P - Auto-promote": "P - 自动提升",
    "Spacebar - Pause": "空格键 - 暂停",
    "Yin Yang": "阴阳",
    "You wield an unlimited power, making you unstoppable. By ruling with an iron fist, everyone in the Arcane Association has to obey your commands.": "你拥有无限的力量，让你势不可挡。 通过铁腕统治，奥术协会的每个人都必须服从你的命令。",
    "\"Void Manipulation\"": "“虚空操纵”",
    "\"You are now part of something\n                                        bigger than yourself...\"": "\"你现在是比你自己更大的事物的一部分...\"",
    "\"You have to embrace the Void...\"": "“你必须拥抱虚空……”",
    "1 + the max level of the class or ability / 10.": "1 + 职业或能力的最高等级 / 10。",
    "Arrow Keys - Menu navigation": "箭头键 - 菜单导航",
    "Battle Tactics lvl": "战斗战术 等级",
    "Muscle Memory lvl": "肌肉记忆 等级",
    "Yin Yang lvl": "阴阳等级",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //原样
    '2 whole centuries': '200年',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\t\t\t\t\t\t\t\t\t\t": "\t\t\t\t\t\t\t\t\t\t",
    "Veteran Knight level ": "资深骑士等级 ",
    "Strength level ": "力量等级 ",
    "Farmer level ": "农民等级 ",
    "Productivity level ": "生产力等级 ",
    "Concentration level ": "专注等级 ",
    "Beggar level ": "乞丐等级 ",
    "Miner level ": "矿工等级 ",
    "Fisherman level ": "渔夫等级 ",
    "Meditation level ": "冥想等级 ",
    "Squire level ": "护卫等级 ",
    "Veteran footman level ": "资深步兵等级 ",
    "Elite knight level ": "骑士等级 ",
    "Knight level ": "骑士等级 ",
    "Holy Knight level ": "圣骑士等级 ",
    "Footman level ": "步兵等级 ",
    "Blacksmith level ": "铁匠等级 ",
    "Bargaining level ": "讨价还价等级 ",
    "Mage level ": "法师等级 ",
    "Evil control level ": "邪恶控制等级 ",
    "Chairman level ": "会长等级 ",
    "Dark influence level ": "邪恶势力等级 ",
    "Time warping level ": "时间扭曲等级 ",
    "Wizard level ": "巫师等级 ",
    "Student level ": "学生等级 ",
    "Master Wizard level ": "大师级法师等级 ",
    "Intimidation level ": "威胁等级 ",
    "Legendary knight level ": "传奇骑士等级 ",
    "Immortality level ": "永生等级 ",
    "Demon Training level ": "魔鬼训练等级 ",
    "Apprentice Mage level ": "学徒法师等级 ",
    "ability unlocked!": "能力解锁！",
    "Eternal Wanderer level ": "永恒的流浪者等级 ",
    "Void Symbiosis level": "虚空共生等级",
    "Void Symbiosis lvl": "虚空共生 等级",
    "Void Wraith lvl": "虚空幽灵 等级",
    "Absolute Wish lvl": "绝对愿望 等级",
    "Abyss Anomaly lvl": "深渊异常等级",
    "Adept Mage lvl": "熟练法师lvl",
    "All Seeing Eye lvl": "全视之眼 等级",
    "Apprentice Mage lvl": "学徒法师等级",
    "Archmage lvl": "大魔导师等级",
    "Astral Body lvl": "星体 等级",
    "Blood Meditation lvl": "血液冥想 等级",
    "Brainwashing lvl": "洗脑lvl",
    "Ceaseless Abyss lvl": "无尽深渊 等级",
    "Chronomancer lvl": "时空术士 等级",
    "Corrupted level": "腐化等级",
    "Corrupted lvl": "腐化等级",
    "Dark Influence lvl": "邪恶势力等级",
    "Dark Knowledge lvl": "黑暗知识 等级",
    "Demon Training lvl": "恶魔训练等级",
    "Demon's Wealth lvl": "恶魔的财富 等级",
    "Evil Control lvl": "邪恶控制等级",
    "Imperator lvl": "帝王等级",
    "Life Essence lvl": "生命精华等级",
    "Mana Control lvl": "法力控制等级",
    "Master Wizard lvl": "大师级法师",
    "Mind Seize lvl": "头脑风暴 等级",
    "Parallel Universe lvl": "平行宇宙等级",
    "Temporal Dimension lvl": "时间维度 等级",
    "Time Loop lvl": "时间循环 等级",
    "Time Warping lvl": "时间扭曲等级",
    "Void Amplification lvl": "虚空增幅等级",
    "Void Fiend lvl": "虚空恶魔等级",
    "Void Influence lvl": "虚空影响等级",
    "Void Lord lvl": "虚空领主等级",
    "Void Lord level": "虚空领主等级",
    "Void Reaver lvl": "虚空掠夺者等级",
    "Void Slave lvl": "虚空奴隶等级",
    "Chronomancer level ": "时空术士等级 ",
    "Centenary lvl": "百年纪念 等级",
    "All Seeing Eye level ": "全视之眼等级 ",
    "Imperator level ": "帝王等级 ",
    "Adept Mage level ": "熟练法师等级",
    "Archmage level ": "大魔导师等级 ",
    "Centenary level ": "百年纪念等级 ",
    "Sigma Proioxis lvl": "西格玛益生菌等级",
    "Eternal Wanderer lvl": "永恒的流浪者等级",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n\t\t\t\t\t\t\t\t\t\t": "\n\t\t\t\t\t\t\t\t\t\t",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加多空格：\n(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)B evil$/, '$1B 邪恶'],
    [/^([\d\.]+)k essence$/, '$1k 精华'],
    [/^([\d\.]+)k evil$/, '$1k 邪恶'],
    [/^x([\d\.]+) Evil gain$/, 'x$1 邪恶收益'],
    [/^x([\d\.]+) Longer lifespan$/, 'x$1 更长的寿命'],
    [/^x([\d\.]+) Military pay$/, 'x$1 军队收入'],
    [/^x([\d\.]+) Gamespeed$/, 'x$1 游戏速度'],
    [/^x([\d\.]+) Job pay$/, 'x$1 工作收入'],
    [/^x([\d\.]+) Class Pay$/, 'x$1 职业收入'],
    [/^x([\d\.]+) Military XP$/, 'x$1 军队经验'],
    [/^x([\d\.]+) T.A.A. XP$/, 'x$1 T.A.A. 经验'],
    [/^x([\d\.]+) Longer Lifespan$/, 'x$1 更长的使用寿命'],
    [/^x([\d\.]+) Galactic Council XP$/, 'x$1 银河委员会 经验'],
    [/^x([\d\.]+) Reduced Expenses$/, 'x$1 费用减少'],
    [/^x([\d\.]+) Essence Gain$/, 'x$1 精华增益'],
    [/^x([\d\.]+) Evil Gain$/, 'x$1 邪恶增益'],
    [/^x([\d\.]+) Reduced Happiness$/, 'x$1 幸福感降低'],
    [/^x([\d\.]+) Magic XP$/, 'x$1 魔法经验'],
    [/^x([\d\.]+) Void Manipulation XP$/, 'x$1 虚空操纵经验'],
    [/^x([\d\.]+) Fundamentals XP$/, 'x$1 基础知识经验'],
    [/^x([\d\.]+) Strength XP$/, 'x$1 力量经验'],
    [/^x([\d\.]+) The Void XP$/, 'x$1 虚空经验'],
    [/^x([\d\.]+) Military Pay$/, 'x$1 军队收入'],
    [/^x([\d\.]+) T.A.A. xp$/, 'x$1 奥术协会经验'],
    [/^x([\d\.]+) Magic xp$/, 'x$1 魔法经验'],
    [/^x([\d\.]+) Skill xp$/, 'x$1 技能经验'],
    [/^x([\d\.]+) Strength xp$/, 'x$1 力量经验'],
    [/^x([\d\.]+) Military xp$/, 'x$1 军队经验'],
    [/^x([\d\.]+) Job xp$/, 'x$1 工作经验'],
    [/^x([\d\.]+) Ability XP$/, 'x$1 能力经验'],
    [/^x([\d\.]+) Expenses$/, 'x$1 费用'],
    [/^x([\d\.]+) Happiness$/, 'x$1 幸福'],
    [/^x([\d\.]+) Class XP$/, 'x$1 职业经验'],
    [/^x([\d\.]+) Essence \+ Evil Gain$/, 'x$1 精华 \+ 邪恶增益'],
    [/^x([\d\.]+) All XP$/, 'x$1 全部经验'],
    [/^x([\d\.]+) Max Lvl Multiplier$/, 'x$1 最大等级乘数'],
    [/^x([\d\.]+) All xp$/, 'x$1 全部经验'],
    [/^(.+) Concentration level (.+), Chairman level (.+)$/, '$1 专注等级 $2，会长等级 $3'],
    [/^Abyss God level (.+), Dark Influence level (.+), Void Influence level (.+)$/, '深渊之神等级 $1，邪恶势力等级 $2, 虚空影响等级 $3'],
    [/^Sigma Proioxis level (.+), Absolute Wish level (.+), Dark Knowledge level (.+)$/, '西格玛益生菌等级 $1，绝对的愿望等级 $2, 黑暗知识等级 $3'],
    [/^Sigma Proioxis level (.+), Absolute Wish level (.+)$/, '西格玛益生菌等级 $1，绝对的愿望等级 $2'],
    [/^Battle Tactics level (.+), Holy Knight level (.+)$/, '战斗战术等级 $1，圣骑士等级 $2'],
    [/^Void Influence level (.+), Abyss Anomaly level (.+)$/, '虚空影响等级 $1，深渊异常等级 $2'],
    [/^Void Embodiment level (.+), Void Lord level (.+)$/, '虚空化身等级 $1，虚空领主等级 $2'],
    [/^Mana Control level (.+), Apprentice Mage level (.+)$/, '法力控制等级 $1，学徒法师等级 $2'],
    [/^Mana Control level (.+), Adept Mage level (.+)$/, '法力控制等级 $1，熟练法师等级 $2'],
    [/^Mana Control level (.+), Veteran Knight level (.+)$/, '法力控制等级 $1，资深骑士等级 $2'],
    [/^Mana Control level (.+), Productivity level (.+), Chronomancer level (.+)$/, '法力控制等级 $1，生产力等级 $2，时空术士等级 $3'],
    [/^Mana Control level (.+), Productivity level (.+)$/, '法力控制等级 $1，生产力等级 $2'],
    [/^Mana Control level (.+), Abyss Anomaly level (.+)$/, '法力控制等级 $1，深渊异常等级 $2'],
    [/^Mana Control level (.+), Battle Tactics level (.+)$/, '法力控制等级 $1，战斗战术等级 $2'],
    [/^Mana Control level (.+), Battle Tactics level (.+), Holy Knight level (.+)$/, '法力控制等级 $1，战斗战术等级 $2，圣骑士等级 $3'],
    [/^Mana Control level (.+), Student level (.+)$/, '法力控制等级 $1，学生等级 $2'],
    [/^Mana Control level (.+), Master Wizard level (.+)$/, '法力控制等级 $1，大师级法师等级 $2'],
    [/^Mana Control level (.+), Meditation level (.+)$/, '法力控制等级 $1，冥想等级 $2'],
    [/^Mana Control level (.+), Meditation level (.+), Archmage level (.+)$/, '法力控制等级 $1，冥想等级 $2，大魔导师等级 $3'],
    [/^Mana Control level (.+), Chairman level (.+)$/, '法力控制等级 $1，会长等级 $2'],
    [/^Mana Control level (.+)$/, '法力控制等级 $1'],
    [/^Void Influence (.+)$/, '虚空影响等级 $1'],
    [/^Temporal Dimension level (.+)$/, '时间维度等级 $1'],
    [/^Void Slave level (.+), Chairman level (.+)$/, '虚空奴隶等级 $1，会长等级 $2'],
    [/^Mana Control level (.+)\/$/, '法力控制等级 $1\/'],
    [/^Void Slave level (.+)\/$/, '虚空奴隶等级 $1\/'],
    [/^Battle Tactics level (.+), Centenary level (.+)$/, '战斗战术等级 $1，百年纪念等级 $2'],
    [/^Battle Tactics level (.+), Footman level (.+)$/, '战斗战术等级 $1，步兵等级 $2'],
    [/^Brainwashing level (.+), Void Slave level (.+)$/, '洗脑等级 $1，虚空奴隶等级 $2'],
    [/^Battle Tactics level ([\d\.]+)\/$/, '战斗战术等级 $1\/'],
    [/^(.+) Cosmic Longevity level (.+)$/, '$1 宇宙寿命等级 $2'],
    [/^(.+) Archmage level (.+)$/, '$1 大魔导师等级 $2'],
    [/^(.+) Chronomancer level (.+)$/, '$1 时空术士等级 $2'],
    [/^If you decide to embrace evil, all of your levels, coins and even max levels will be reset.\n(.+)You will be reborn as a fresh slate. However, you will unlock a new line of skills and gain$/, '如果你决定拥抱邪恶，那么你所有的等级、金币甚至最高等级都将被重置。你将以崭新的面貌重生。然而，你将解锁一个新的技能线并获得'],
    [/^Your gut instinct was right. The moment you hit the grand age of 200, you hear an ominous hum coming from the amulet.\n(.+)A mouth emerges from its surface and begins to cackle, and proceeds to say\: "So you've made it this far... Are you ready to embrace evil\?"$/, '你的直觉是对的。当你到达200岁的时候，你会听到护身符发出不祥的嗡嗡声。一张嘴从它的表面露出来，咯咯地笑着说\:“你已经走到这一步了……你准备好迎接邪恶了吗\?”'],
    [/^You stumble across a strange looking amulet on your 25th birthday. It does not look like\n(.+)it has any worth on the market given that it's made from cheap-looking copper. However, you\n(.+)feel a weird urge to keep the amulet, so you slip it into your pocket for safekeeping.$/, '你在25岁生日时偶然发现了一个奇怪的护身符。它看起来不像在市场上有任何价值，因为它是由看起来很便宜的铜制成的。然而，你有一种奇怪的冲动想要保存这个护身符，所以你把它放进口袋里妥善保管。'],
    [/^Concentration level (.+)\/(.+), Meditation level (.+)\/$/, '专注等级 $1\/$2，冥想等级 $3\/'],
    [/^On your 65th birthday, you once again encounter the strange, unexplained shivering from your\n(.+)amulet. But this time, a living eyeball emerges from the centre. Although terribly frightened,\n(.+)you realise you do not have many years to live left anyway so you consider touching the eye\n(.+)to see what happens.$/, '在你65岁生日时，你再次遇到奇怪的，无法解释的颤抖从你的护身符。但这一次，一个活生生的眼球从中心出现了。尽管非常害怕，你意识到你已经没有多少年可以活了，所以你考虑触摸一下眼睛，看看会发生什么。'],
    [/^([\d\.]+)\/([\d\.]+), Veteran footman level (.+)\/$/, '$1\/$2, 资深步兵等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Blacksmith level (.+)\/$/, '$1\/$2, 铁匠等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Immortality level (.+)\/$/, '$1\/$2, 永生等级 $3\/'],
    [/^([\d\.]+)\/(.+), Mage level (.+)\/$/, '$1\/$2, 法师等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Footman level (.+)\/$/, '$1\/$2, 步兵等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Veteran knight level (.+)\/$/, '$1\/$2, 资深骑士等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Mana control level (.+)\/$/, '$1\/$2, 法力控制等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Battle tactics level (.+)\/$/, '$1\/$2, 战斗战术等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Holy knight level (.+)\/$/, '$1\/$2, 圣骑士等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Apprentice mage level (.+)\/$/, '$1\/$2, 学徒法师等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Elite knight level (.+)\/$/, '$1\/$2, 精英骑士等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Student level (.+)\/$/, '$1\/$2, 学生等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Knight level (.+)\/$/, '$1\/$2, 骑士等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Miner level (.+)\/$/, '$1\/$2, 矿工等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Fisherman level (.+)\/$/, '$1\/$2, 渔夫等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Strength level (.+)\/$/, '$1\/$2, 力量等级 $3\/'],
    [/^([\d\.]+)k\/([\d\.]+)k, Dark influence level (.+)\/$/, '$1k\/$2k, 邪恶势力等级 $3\/'],
    [/^([\d\.]+)k\/([\d\.]+)k, Wizard level (.+)\/$/, '$1k\/$2k, 巫师等级 $3\/'],
    [/^([\d\.]+)k\/([\d\.]+)k, Chairman level (.+)\/$/, '$1k\/$2k, 会长等级 $3\/'],
    [/^([\d\.]+)k\/([\d\.]+)k, Evil control level (.+)\/$/, '$1k\/$2k, 邪恶控制等级 $3\/'],
    [/^([\d\.]+)k\/([\d\.]+)k, Intimidation level (.+)\/$/, '$1k\/$2k, 威胁等级 $3\/'],
    [/^([\d\.]+)k\/([\d\.]+)k, Time warping level (.+)\/$/, '$1k\/$2k, 时间扭曲等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Productivity level (\d+)\/$/, '$1\/$2, 生产力等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Squire level (\d+)\/$/, '$1\/$2, 护卫等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Meditation level (\d+)\/$/, '$1\/$2, 冥想等级 $3\/'],
    [/^([\d\.]+) \+ the max level of the skill or job \/ (\d+).$/, '$1 \+ 你的技能或工作的最高等级 \/ $2。'],
    [/^On your 45th birthday, you feel the amulet shiver uncontrollably in your pocket. You take it\n(.+)out and the constant shivering suddenly stops. More to your bizarre surprise, you notice\n(.+)a strange etching on the centre of the amulet.$/, '在你45岁生日的时候，你感觉到你口袋里的护身符在不受控制地颤抖。你把它拿出来，不停的颤抖突然停止了。更让你惊讶的是，你会注意到↵这个护身符的中心有一个奇怪的蚀刻。'],
    [/^By touching the eyeball, you will be reborn and have to restart life again, losing all your levels and coins.\n(.+)However, you will gain$/, '通过触摸眼球，你将获得重生，你将会失去所有等级和金币。然而,你会得到'],
    [/^法力控制等级 (.+)，战斗战术等级 (.+), Holy knight level (.+)\/$/, '法力控制等级 $1，战斗战术等级 $2, 圣骑士等级 $3\/'],
    [/^Mana control level (\d+)\/(\d+), Student level (\d+)\/$/, '法力控制等级 $1\/$2，学生等级 $3\/'],
    [/^Battle tactics level (\d+)\/(\d+), Knight level (\d+)\/$/, '战斗战术等级 $1\/$2，骑士等级 $3\/'],
    [/^Battle tactics level (\d+)\/(\d+), Footman level (\d+)\/$/, '战斗战术等级 $1\/$2，步兵等级 $3\/'],
    [/^Bargaining level (\d+)\/(\d+), Blacksmith level (\d+)\/$/, '议价等级 $1\/$2，铁匠等级 $3\/'],
    [/^(\d+)\/(\d+), Battle tactics level (.+)\/$/, '$1/$2，战斗战术等级 $3\/'],
    [/^(\d+)\/(\d+), Mage level (.+)\/$/, '$1/$2，法师等级 $3\/'],
    [/^(\d+)\/(\d+)k, Chairman level (.+)\/$/, '$1/$2k，会长等级 $3\/'],
    [/^(\d+)\/(.+), Battle tactics level (.+), Holy knight level (.+)\/$/, '$1/$2，战斗战术等级 $3，圣骑士等级 $4\/'],
    [/^(\d+) essence$/, '$1 精华'],
    [/^([\d\.]+) evil$/, '$1 邪恶'],
    [/^([\d\.]+)M evil$/, '$1M 邪恶'],
    [/^([\d\.]+)K evil$/, '$1K 邪恶'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);